apiVersion: v1
kind: Service
metadata:
  labels:
    app: mage-sim
  name: mage-sim
  namespace: default
spec:
  ports:
  - name: "http-port"
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: mage-sim
  sessionAffinity: None
  type: NodePort
