apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mage-sim
  name: mage-sim
  namespace: mage-sim
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mage-sim
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mage-sim
    spec:
      containers:
      - image: doll1av/mage:v5
        name: mage
        ports:
        - containerPort: 8000
        resources: {}
status: {}